// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSDPayslip.Data;

namespace OSDPayslip.Data.Migrations
{
    [DbContext(typeof(OSDPayslipDbContext))]
    [Migration("20190903112117_update-1820-03092019")]
    partial class update182003092019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OSDPayslip.Models.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeptTeam");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Position");

                    b.Property<string>("StartDay");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OSDPayslip.Models.Models.PayslipDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("ActuaSalary");

                    b.Property<int>("ActualWorkingDay");

                    b.Property<double?>("Allowance");

                    b.Property<double?>("BasicSalary");

                    b.Property<double?>("Bonus");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("EmployeeID");

                    b.Property<double?>("FinalizationOfPIT");

                    b.Property<double?>("GrossSalary");

                    b.Property<double?>("HealthInsurance");

                    b.Property<int>("Holidays");

                    b.Property<double?>("IncomeOther");

                    b.Property<double?>("Insurance");

                    b.Property<int>("LeaveBalance");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<double?>("NetIncome");

                    b.Property<int?>("NoOfDependants");

                    b.Property<double?>("OtherDeductions");

                    b.Property<double?>("PaymentFromSocialInsurance");

                    b.Property<double?>("PaymentOther");

                    b.Property<double?>("PersonalIncomeTax");

                    b.Property<int>("RequestID");

                    b.Property<double?>("Salary13Th");

                    b.Property<double?>("SocialInsurance");

                    b.Property<int>("StandardWorkingDay");

                    b.Property<int>("Status");

                    b.Property<double?>("UnemploymentInsurance");

                    b.Property<int>("UnpaidLeave");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("RequestID");

                    b.ToTable("PayslipDetails");
                });

            modelBuilder.Entity("OSDPayslip.Models.Models.RequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("NoOfDeployee");

                    b.Property<int?>("PayslipForMonth");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("RequestDetail");
                });

            modelBuilder.Entity("OSDPayslip.Models.Models.PayslipDetail", b =>
                {
                    b.HasOne("OSDPayslip.Models.Models.Employee", "Employee")
                        .WithMany("PayslipDetails")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("OSDPayslip.Models.Models.RequestDetail", "RequestDetail")
                        .WithMany("PayslipDetails")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
